source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’9.0’
use_frameworks!

target 'BeautifulApp' do
    pod 'Alamofire',    '~>4.1'
    pod 'SnapKit',      '~>3.0.1'
    pod 'Moya’,  	    ‘~>10.0.0'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'MonkeyKing',   '~> 1.1.0'
    pod 'YYWebImage'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = ‘3.0’
        end
    end
end
